### ISSUE TITLE
Issue with articulation-bodies in OnEpisodeBegin

### ISSUE THREAD

**Issue by mathujeyanth** [Unity-Technologies/articulations-robot-demo#36]
**Describe the bug**
I'm unable to move an articulation body to be in a specific configuration in `OnEpisodeBegin`. 

Using the gripper scene in the [Articulation-robots-demo](https://github.com/Unity-Technologies/articulations-robot-demo.git) project to illustrate the issue, I'm attempting to grip the cube in the air before training i.e. in the `OnEpisodeBegin`, but I'm unable to do so since this causes Unity to freeze. I tried using both a simple while loop, but also a coroutine, but did not seem to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the Unity [Articulation-robots-demo](https://github.com/Unity-Technologies/articulations-robot-demo.git) project.
2. Add ML-Agents package and open the GripperScene
3. Create a new script called GripperAgent
4. Insert either in the newly created script:
a.
  ```cs
  public class GripperAgent : Agent
  {
      public GameObject cube;
      Rigidbody rb;
      public GameObject hand;
      PincherController pincherControler;
  
      void Start() {
          pincherControler = hand.GetComponent<PincherController>();
          rb = cube.GetComponent<Rigidbody>();
      }
  
      public override void OnEpisodeBegin()
      {
          rb.useGravity = false;
          rb.position = new Vector3(0.01f,0.6f,0);
          while(pincherControler.grip<0.122f){
              pincherControler.gripState =  GripState.Closing;
              Debug.Log(pincherControler.grip);
          }
      }
      public override void CollectObservations(VectorSensor sensor){}
      public override void OnActionReceived(ActionBuffers actionBuffers){}
  }
  ```
b. 

  ```cs
  public class GripperAgent : Agent
  {
      public GameObject cube;
      Rigidbody rb;
      public GameObject hand;
      PincherController pincherControler;
      public bool finished = false;
  
      void Start() {
          pincherControler = hand.GetComponent<PincherController>();
          rb = cube.GetComponent<Rigidbody>();
      }
  
      public override void OnEpisodeBegin()
      {
          rb.useGravity = false;
          rb.position = new Vector3(0.01f,0.6f,0);
          StartCoroutine(MyCoroutine());
          while(!finished){}
      }
      IEnumerator MyCoroutine()
      {
          while(pincherControler.grip<0.122f){
              pincherControler.gripState =  GripState.Closing;
              Debug.Log(pincherControler.grip);
              yield return new WaitForSeconds(Time.fixedDeltaTime);
          }
          finished = true;
      }
      public override void CollectObservations(VectorSensor sensor){}
      public override void OnActionReceived(ActionBuffers actionBuffers){}
  }
  ```
5. Attach a GripperAgent script to the root containing the gripper gameobject and set `Max Step` to 1000
6. Attach the cube and the HandE(under root) to the GripperAgent script
7. Attach Decision Requester script to the root
8. Starting the Unity Player, then causes Unity to freeze.

**Environment**
- Unity Version: Unity 2021.1.2f1
- OS + version: Windows 10, 19042.928
- _ML-Agents version_: ML-Agents v1,9.1 (Release 16)

**Comment by mrpropellers** [comment]
Hi @mathujeyanth!  As Chris has pointed out, this is not a bug in ml-agents nor the articulations demo. In both code snippets, your while loops are blocking the execution of Unity's game loop, and as such will freeze Unity. You must exit your functions to allow the update loops to continue to run. The condition in your first snippet, `while(pincherControler.grip<0.122f)`, can never be satisfied since the function never exits. Similarly, on the second one, you will be stuck in `while(!finished)` as soon as your coroutine hits its first `yield` statement. Please note, from the [Unity docs](https://docs.unity3d.com/Manual/Coroutines.html), that Coroutines are not threaded. They are functions which have been broken up into chunks to be executed in serial on the main game thread.

**Comment by mathujeyanth** [comment]
Hi, thank you I didn't know that. I assumed they were threaded so it makes sense why Unity would freeze then. Though, then in this example, how would I be able to achieve grasping the cube before `OnEpisodeBegin` is finished? 
I've looked into threads, but from what I could gather Unity's Api is not thread safe.
Furthermore, since this is not an direct bug issue should I close this issue and move it to the ML-Agents forum page or keep it as it is?

**Comment by mrpropellers** [comment]
It's up to you whether you'd like to move this to the forum or continue it here. If you want to try and open up a more general discussion, the forum is definitely better, but if you just need a few technical questions answered, it's fine to leave this issue open and I can do my best to help you out.

If you want a controller to drive the grasper closed, utilizing the physics engine, then I don't think it's possible to do so inside the scope of `OnEpisodeBegin`, which is only meant to be used for setting initial state of your episode. A couple things to consider:

1. Could you set the instantaneous state of the gripper to closed by setting the position of the appropriate joints rather than rely on a controller to close it?
2. Does the gripper _need_ to be closed at the beginning of the episode? Or could you allow it to close during the update loop within an episode, and only collect your observations and compute reward after it's closed?

**Comment by mathujeyanth** [comment]
Thank you, I think I'll attempt implementing the agent where it closes the gripper during the update loop and collect observation after, as you have suggested. If that does not work I'll be creating a forum post on how to approach this, since that seems more appropriate.
