### ISSUE TITLE
Articulation not movable via Transform

### ISSUE THREAD

**Issue by RichSidley** [Unity-Technologies/articulations-robot-demo#39]
Not sure where to report this, so here goes -- sorry if wrong place.

Made a figure using Articulation Bodies and it works fine for everything except direct setting of its transform upon game Initialize or OnEpisodeBegin when training under ML-Agents. Any non-Articulation Body can be moved without problem, so it is not a coding issue but seems to be a bug in Unity.

**Comment by at669** [comment]
Hi @RichSidley, this is the intended behavior of ArticulationBodies. The position of any non-root ArticulationBodies is defined in the reduced space relative to the parent, which could result in no reduced space coordinate matching a specified world-space pose. That being said, if you would like to move an ArticulationBody, [`TeleportRoot()`](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/ArticulationBody.TeleportRoot.html) is the recommended method.

In the future, questions like this may be better fielded in the [Robotics Forum](https://forum.unity.com/forums/robotics.623/). Hope this helps!

**Comment by at669** [comment]
Hi, I wasn't able to fully recreate your issue. Using TeleportRoot moved the root and connected ArticulationBodies for me using the following lines:

```
var ab = GetComponent<ArticulationBody>();
ab.TeleportRoot(new Vector3(2, 4, 2), Quaternion.identity);
```

Could you provide more details on your bug by providing the following details?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Environment (please complete the following information, where applicable):**
- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]

**Additional context**
Add any other context about the problem here.
